server:
   port: 8099
   
eureka:
  client:
    registerWithEureka: false    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  host: #para seguridad
    connect-timeout-millis: 100000 #para seguridad
    socket-timeout-millis: 100000 #para seguridad
  routes:
    uaa: #para seguridad
       path: /uaa/**
       sensitiveHeaders: #para seguridad
       serviceId: AUTH-SERVER
    forma1:
        path: /micro-client/**
        sensitiveHeaders: #para seguridad
        url: http://localhost:8085/ #https://spring-micro-mito.herokuapp.com/ 
    forma2:
        path: /micro-api/**
        sensitiveHeaders: #para seguridad
        serviceId: MICRO-CLIENTE
    #nodejs:
        #path: /node-client/**
        #sensitiveHeaders: #para seguridad
        #url: http://localhost:3000/ #https://node-mito.herokuapp.com/
        
        




